steps:
  - name: 'gcr.io/k8s-skaffold/pack'
    entrypoint: 'pack'
    args: ['build', '--builder=gcr.io/buildpacks/builder', '--publish', 'europe-west1-docker.pkg.dev/test-ci-cd-374510/ci-cd/test:v3']