steps:
  - name: 'gcr.io/k8s-skaffold/pack'
    entrypoint: 'pack'
    args: ['build', '--builder=gcr.io/buildpacks/builder', '--publish', 'europe-west3-docker.pkg.dev/test-ci-cd-371415/test/ci-cd:$SHORT_SHA']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
    - '-c'
    - > 
      gcloud deploy releases create release-$BUILD_ID
      --delivery-pipeline=ci-cd-service-test
      --region=europe-west3
      --source=./
      --images=europe-west3-docker.pkg.dev/test-ci-cd-371415/test/ci-cd:$SHORT_SHA