apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: ci-cd-test
build:
  artifacts:
  - image: europe-west3-docker.pkg.dev/test-ci-cd-371415/test/ci-cd
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - deploy-dev.deployment.yaml
