---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: ci-cd
    name: ci-cd
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: ci-cd
    template:
      metadata:
        labels:
          app: ci-cd
      spec:
        containers:
          - name: ci-cd
            image: ci-cd
            ports:
              - containerPort: 3000
            resources:
              limits:
                cpu: "0.1"
                memory: "256Mi"
                ephemeral-storage: "1Gi"
              requests:
                cpu: "0.05"
                memory: "128Mi"
                ephemeral-storage: "512Mi"